# This workflow close issue and add comment after the issue labaled as 'inactive'

name: Close issue
on:
  issues:
    types:
      - labeled
jobs:
  close-inactive-issue:
    if: github.event.label.name == 'Inactive'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue due to inactivity
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            This issue is closed due to inactivity. If the issue continue, please open a new one.
